### ISSUE TITLE
建议再提供一个可自定义枚举类型，让用户根据自己的业务需求实现

### ISSUE THREAD

**Issue by single-dh** [Jinxiansen/Guardian#2]

**Comment by Jinxiansen** [comment]
嗯，已经添加了，最新3.0.0版本。

`.package(url: "https://github.com/Jinxiansen/Guardian.git", from: "3.0.0")`

你可以修改 package.swift 文件中这个版本号为 3.0.0 ，然后执行以下命令更新。

`vapor clean && vapor build && vapor xcode -y `

另外，新增了 demo，可以下载一看。😚
